@startuml

title US001 - Create a map (SD)

autonumber
actor Editor

activate Editor

	Editor -> CreateMapUI: Select create map function

	activate CreateMapUI
		CreateMapUI --> CreateMapUI : readName()
		CreateMapUI --> Editor: Ask for map name
	deactivate CreateMapUI
		Editor -> CreateMapUI: Give the map name
	activate CreateMapUI
		CreateMapUI --> CreateMapUI : validCharacters()
		CreateMapUI --> CreateMapUI : readHeight()
		CreateMapUI --> Editor: Ask for map height
	deactivate CreateMapUI
		Editor -> CreateMapUI: Give the map height

	activate CreateMapUI
		CreateMapUI --> CreateMapUI : readLength()
		CreateMapUI --> Editor: Ask for map length
	deactivate CreateMapUI
		Editor -> CreateMapUI: Give the map length

	activate CreateMapUI
		CreateMapUI --> CreateMapUI : readScale()
		CreateMapUI --> Editor: Ask for map scale
	deactivate CreateMapUI
		Editor -> CreateMapUI: Give the map scale

    activate CreateMapUI
		CreateMapUI --> CreateMapUI : isValidInt(length)
		CreateMapUI --> CreateMapUI : isValidInt(height)
		CreateMapUI --> CreateMapUI : isValidInt(scale)

		CreateMapUI -> CreateMapController: createMap(name, length, height)

		activate CreateMapController
			CreateMapController -> Simulator : getSimulator()
			activate Simulator
				Simulator --> CreateMapController : Simulator
			deactivate Simulator

			CreateMapController -> Simulator : createMap(name, length, height)
			activate Simulator
				Simulator --> Simulator : isNameUnique(name)
				Simulator -> Map : Map(name, length, height)
			deactivate Simulator

				activate Map
					Map --> Simulator : map
				deactivate Map

				activate Simulator
				    Simulator -> MapRepository : addMap(Map)
				deactivate Simulator
				    activate MapRepository
				     MapRepository  --> Simulator
				deactivate MapRepository
				activate Simulator
				     Simulator --> CreateMapController : Map
				deactivate Simulator


			CreateMapController --> CreateMapUI: map created status
		deactivate CreateMapController
		CreateMapUI --> Editor: Display map created confirmation
deactivate Editor

@enduml
