package pt.ipp.isep.dei.dto;

import pt.ipp.isep.dei.domain.City;

public class CityDTO {

    public static CityDTO toDTO(City city) {
        if (city == null)
            return null;
        CityDTO dto = new CityDTO();
        //dto (city.getName());
        //dto.setEmail(city.getEmail());
        return dto;
    }

    public static City toEntity(CityDTO dto) {
        if (dto == null)
            return null;
        //City city = new City();
        //city.setName(dto.getName());
        //city.setEmail(dto.getEmail());
        // ID would typically be generated by the database
        return null;
    }

}
